### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tonku** [point-source/supabase-tenant-rbac#10]
do we need this check ? 
begin IF session_user = 'authenticator' THEN --------------------------------------------
-- To disallow any authenticated app users
-- from editing claims, delete the following
-- block of code and replace it with:
-- RETURN FALSE;
--------------------------------------------

as the rpc call needs to pass the auth token for functions to execute, I assume that the pg functions are executed in the authenticated user's context?

**Comment by point-source** [comment]
Not necessarily. These procedures can be called by:

- Edge functions using the service_role key (which bypasses auth)
- Cron jobs from pg_cron which are invoked by the database itself as some predefined user
- Other db functions which are using the SECURITY DEFINER privilege

My current understanding is that any of these cases could result in the function being called in such a way that the session_user != "authenticator" and that no JWT validation or auth has taken place at all.
