### ISSUE TITLE
create a "package"?

### ISSUE THREAD

**Issue by kiwicopple** [point-source/supabase-tenant-rbac#12]
hey team, supabase ceo 👋 

Would you like to turn this into a database package for our upcoming Launch Week? Creating a package would allow users to simply run something like:

```sql
select dbdev.install("pointsource-rbac");

create extension "rbac";
```

the "dbdev" command  would pull the package from here: https://database.dev/

Here are some docs on how to convert this into a package: https://supabase.github.io/dbdev/publish-extension/

And you can see some of my own examples here: https://github.com/kiwicopple/pg-extensions/

Let me know if you need help!

**Comment by point-source** [comment]
Absolutely! I'd love to do this. I left some questions here last time: https://github.com/point-source/supabase-tenant-rbac/issues/2

Help would be appreciated

**Comment by kiwicopple** [comment]
ah I'm sorry @point-source - I didn't realise I created 2 issues 😓 . closing this - let's move to the other
