### ISSUE TITLE
Security definer functions search_path not set

### ISSUE THREAD

**Issue by glib-0** [point-source/supabase-tenant-rbac#18]
Pretty new to SQL and not sure if I'm just dumb, but you haven't set the search_path in your security definer functions.

Supabase docs: [https://supabase.com/docs/guides/database/functions?language=js&example-view=data#security-definer-vs-invoker](url)
![supabase_docs](https://github.com/point-source/supabase-tenant-rbac/assets/112022846/da5e5726-3733-4b50-bbce-b9139272bf3d)

Also, on Postgres docs it says pg_temp is searched first by default: [https://www.postgresql.org/docs/9.1/sql-createfunction.html#SQL-CREATEFUNCTION-SECURITY](url)

**Comment by point-source** [comment]
Woah, good catch! Thank you. I am also somewhat new to SQL (~1-2 years) and by no means an expert. I appreciate the heads up on this. I have a few bug fixes incoming

**Comment by point-source** [comment]
I have a preliminary fix for this that I am working on in the [1.0.0](https://github.com/point-source/supabase-tenant-rbac/tree/1.0.0) branch

**Comment by point-source** [comment]
This should be fixed as of 1.0.0 release
