### ISSUE TITLE
delete permission on groups correct?

### ISSUE THREAD

**Issue by jniclas** [point-source/supabase-tenant-rbac#24]
Hi! Thanks for the awesome project! While I am integrating it to my own project:
Should the permission at https://github.com/point-source/supabase-tenant-rbac/blob/main/supabase/migrations/20240512101038_add_rls_policies.sql#L56 be "group.delete" and not "delete"? So that it matches https://github.com/point-source/supabase-tenant-rbac/blob/main/examples/triggers/auto_group_permissions.sql#L10 ?

**Comment by jziggas** [comment]
Nice catch!

**Comment by point-source** [comment]
Yep, you are right! Will fix today. Thanks ❤️
