### ISSUE TITLE
Removing a user from a group does not remove the group entry in `raw_app_meta_data` and breaks `is_group_member`

### ISSUE THREAD

**Issue by fnimick** [point-source/supabase-tenant-rbac#4]
To duplicate:

- create a group and a user
- add the user to the group in `group_users`
- remove the user from the group
- observe that `raw_app_meta_data` still contains a reference to the group with an empty array, e.g. `{"groups": {"82b969d7-e1e6-4ae6-a731-bea26e849fb2": []}, "provider": "email", "providers": ["email"]}
- observe that `is_group_member()` still returns true for this user, even though all roles have been removed

This occurs because `is_group_member` simply checks for the presence of the group key in the `groups` object, rather than checking for any roles being present; in addition, `update_user_roles` does not remove the group key from the `groups` object once all roles have been removed.

**Comment by point-source** [comment]
I've merged yours changes. Closing as fixed.
