### ISSUE TITLE
Add invite feature

### ISSUE THREAD

**Issue by bangdragon** [point-source/supabase-tenant-rbac#7]
As you said:
```
I've also recently created an invite system built on this and supabase edge functions which allows group owners to generate a token which other users can use to join their group with a specific pre-selected role. I have not yet extensively tested it but if you are interested in this code as well
 ```
Please add this feature. Thanks

**Comment by bangdragon** [comment]
I have one question. In this following code:
```
set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.set_group_owner()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
	begin
		IF auth.uid() IS not NULL THEN 
		insert into public.group_users(group_id, user_id, role) values(new.id, auth.uid(), 'owner');
		end if;
		return new;
	end;
$function$
;

CREATE TRIGGER on_insert_set_group_owner AFTER INSERT ON public.groups FOR EACH ROW EXECUTE FUNCTION set_group_owner();
```
Why need to set check_function_bodies = off;

**Comment by point-source** [comment]
> Why need to set check_function_bodies = off;

Actually, we don't. Feel free to remove or skip that. It gets automatically added by the diff tool when I use supabase's cli to create the migration scripts.

**Comment by point-source** [comment]
Just popping in to say I haven't forgotten this. Just been busy. This is on my to-do list.

**Comment by nikitastryuk** [comment]
this would be great addition

**Comment by point-source** [comment]
I have [added this in the dev branch](https://github.com/point-source/supabase-tenant-rbac/commit/b91b82066e414b90b0f73f37d5b0e9174a293b8d). An updated TLE is coming soon but is currently blocked by [this bug](https://github.com/supabase/dbdev/issues/159).

**Comment by crllnsmnn** [comment]
@point-source First of all - thank you, great work! I am looking forward to this extension!
Is it possible to extend the invitation logic to allow multiple roles when creating the invitation? This would allow more complicated role setups right after invitation.
